// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9sJfNQ0GrB1NEGyqHd0rYd_htSLGnGIQ',
    appId: '1:441627515569:web:3dce1c6acd2eec820aa090',
    messagingSenderId: '441627515569',
    projectId: 'phx-staging-442422',
    authDomain: 'phx-staging-442422.firebaseapp.com',
    storageBucket: 'phx-staging-442422.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0TFD1b2pGfjA49CJE4SiYTJXgZ1V9LE',
    appId: '1:441627515569:android:387bcc4ceb9162a10aa090',
    messagingSenderId: '441627515569',
    projectId: 'phx-staging-442422',
    storageBucket: 'phx-staging-442422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsyleee1D-3zUh7fNRhCL-r_O3oCRuLHk',
    appId: '1:441627515569:ios:a27c19f11cef4fb20aa090',
    messagingSenderId: '441627515569',
    projectId: 'phx-staging-442422',
    storageBucket: 'phx-staging-442422.firebasestorage.app',
    iosClientId: '441627515569-t93g55d4dmkkc1udv8o6mc9r4on1v72u.apps.googleusercontent.com',
    iosBundleId: 'io.phoenixtechnologies.phoenix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsyleee1D-3zUh7fNRhCL-r_O3oCRuLHk',
    appId: '1:441627515569:ios:a27c19f11cef4fb20aa090',
    messagingSenderId: '441627515569',
    projectId: 'phx-staging-442422',
    storageBucket: 'phx-staging-442422.firebasestorage.app',
    iosClientId: '441627515569-t93g55d4dmkkc1udv8o6mc9r4on1v72u.apps.googleusercontent.com',
    iosBundleId: 'io.phoenixtechnologies.phoenix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9sJfNQ0GrB1NEGyqHd0rYd_htSLGnGIQ',
    appId: '1:441627515569:web:f9ea9ec3a90ce7610aa090',
    messagingSenderId: '441627515569',
    projectId: 'phx-staging-442422',
    authDomain: 'phx-staging-442422.firebaseapp.com',
    storageBucket: 'phx-staging-442422.firebasestorage.app',
  );
}
